apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: three-tier
type: Opaque
data:
  mongo-root-password: VGhyZWUtVGllci1Qcm9qZWN0          # Three-Tier-Project
  mongo-root-username: YWRtaW4=                          # admin